spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: id
            client-secret: secret
            scope: openid,profile,email
        provider:
          auth0:
            issuer-uri: https://key.region.auth0.com/

logging:
  level:
    org.springframework.security: DEBUG
