spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://key.region.auth0.com/
  rsocket:
    server:
      port: 7635

server:
  port: 7634
logging:
  level:
    org.springframework.security: DEBUG
